#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=re_train_talesemotions
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=;re_train_talesemotions%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ood-generalization-transfer
source activate ACTS
srun python re_train.py --dataset_path "Preprocessed_Data/EmoBank" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/EmotionStimulus" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/GoodNewsEveryone" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/Semeval2018Intensity" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/SentimentalLIAR" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/CancerEmo" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/UsVsThem" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/WASSA22" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415
srun python re_train.py --dataset_path "Preprocessed_Data/XED" --checkpoint_path results/training/TalesEmotions/dataset_TalesEmotions_seed_1234_testsize_0.2_bs_32/checkpoint-2415