#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=train_canceremo
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=;train_canceremo%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ood-generalization-transfer
source activate ACTS
srun python re_train.py --dataset_path "Preprocessed_Data/CancerEmo" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/EmotionStimulus" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/GoodNewsEveryone" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/Semeval2018Intensity" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/SentimentalLIAR" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/TalesEmotions" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/UsVsThem" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/WASSA22" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906
srun python re_train.py --dataset_path "Preprocessed_Data/XED" --checkpoint_path results/training/EmoBank/dataset_EmoBank_seed_1234_testsize_0.2_bs_16/checkpoint-906