#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=train_wassa22
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=;train_wassa22%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ood-generalization-transfer
source activate ACTS
srun python train.py --dataset_path Preprocessed_Data/WASSA22