#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=get_text_embedding_semeval2018
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=;get_text_embedding_semeval2018%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ood-generalization-transfer
source activate ACTS
srun python get_text_embedding.py --dataset_path Preprocessed_Data/Semeval2018Intensity --checkpoint_path results/training/Semeval2018Intensity/dataset_Semeval2018Intensity_seed_1234_testsize_0.2_bs_16/checkpoint-1497