#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=get_task_embeddingxed
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=;get_task_embeddingxed%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ood-generalization-transfer
source activate ACTS
srun python get_task_embedding.py --dataset_path Preprocessed_Data/XED --checkpoint_path results/training/XED/dataset_XED_seed_1234_testsize_0.2_bs_32/checkpoint-4284