#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=get_task_embedding_wassa22
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=;get_task_embedding_wassa22%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ood-generalization-transfer
source activate ACTS
srun python get_task_embedding.py --dataset_path Preprocessed_Data/WASSA22 --checkpoint_path results/training/WASSA22/dataset_WASSA22_seed_1234_testsize_0.2_bs_8/checkpoint-1344